<?php

declare(strict_types=1);

namespace App\Import;

use App\Audit\AuditLog;
use App\Documents\ShipmentDetailsRepository;
use App\Documents\TradeDetailsRepository;
use App\Http\Support\Input;
use App\Inspections\SchedulingService;
use App\Office\ClientService;
use App\Office\ConsignmentService;
use App\Office\InspectionRequestService;
use App\Support\ApiException;
use App\Users\UserAdminService;
use PDO;

/**
 * Bulk import from a CSV, for every kind of record the office types in:
 *
 *   clients              new clients
 *   nxp                  new NXP records (linked to a client by name)
 *   inspection_requests  new inspection requests for existing NXP records
 *   assignments          inspectors assigned to open requests (creates the inspections)
 *   trade_details        trade / banking details on existing NXP records (CCI boxes)
 *   shipment_details     shipment / NESS details, incl. the exchange rate, on inspections
 *   users                new staff accounts
 *
 * Inspection findings are captured by the inspector's device and certificates
 * are generated by the system, so neither is imported.
 *
 * The preview and the real run are the SAME code path: every row is actually
 * written, inside a transaction, and the preview simply rolls that transaction
 * back at the end. So a preview can't disagree with what a commit will do —
 * every rule the normal single-record forms enforce (they go through the same
 * services) applies here too, including the ones the database enforces, like a
 * duplicate key.
 *
 * A commit is all-or-nothing: if any row fails, nothing is written. That is the
 * behaviour people expect of "import this spreadsheet" — a half-loaded file is
 * worse than a rejected one, because you can't tell by looking which half.
 *
 * The two "details" types UPDATE existing records, and only the cells that are
 * filled in: a blank cell leaves the current value as it is, so a sheet with
 * just `nxp_number,exchange_rate` sets exchange rates and touches nothing else.
 */
final class ImportService
{
    public const TYPES = ['clients', 'nxp', 'inspection_requests', 'assignments', 'trade_details', 'shipment_details', 'users'];

    public const LABELS = [
        'clients'             => ['Clients', 'client', 'clients'],
        'nxp'                 => ['NXP records', 'NXP record', 'NXP records'],
        'inspection_requests' => ['Inspection requests', 'inspection request', 'inspection requests'],
        'assignments'         => ['Inspector assignments', 'inspector assignment', 'inspector assignments'],
        'trade_details'       => ['Trade / banking details', 'NXP record', 'NXP records'],
        'shipment_details'    => ['Shipment / NESS details', 'inspection', 'inspections'],
        'users'               => ['Users', 'user', 'users'],
    ];

    /** Where each type's list lives, for after a successful import. */
    public const RETURN_TO = [
        'clients'             => '/console/clients',
        'nxp'                 => '/console/nxp',
        'inspection_requests' => '/console/inspection-requests',
        'assignments'         => '/console/calendar',
        'trade_details'       => '/console/nxp',
        'shipment_details'    => '/console/inspections',
        'users'               => '/console/users',
    ];

    private const TRADE_COLUMNS = [
        'importer_name' => 200, 'importer_address' => 1000, 'nepc_number' => 50, 'exporter_bank_name' => 200,
        'importer_bank_name' => 200, 'bank_reference' => 100, 'invoice_number' => 100, 'invoice_date' => 'date',
        'basis_of_sale' => ['FOB', 'CFR', 'CIF'], 'method_of_payment' => 100, 'freight_charges' => 'money',
        'insurance_charges' => 'money',
    ];

    private const SHIPMENT_COLUMNS = [
        'shipment_date' => 'date', 'shipping_agent' => 200, 'carrier_vessel' => 200, 'loading_ref_no' => 100,
        'container_numbers' => 255, 'packing_details' => 255, 'quality_remark' => 255, 'gross_weight_kg' => 'money',
        'net_weight_kg' => 'money', 'forex_exchange_date' => 'date', 'exchange_rate' => 'rate',
        'ness_charges_paid' => 'money', 'ness_receipt_no' => 100, 'ness_actual_payable' => 'money',
        'ness_balance_paid' => 'money', 'ness_balance_receipt_no' => 100,
    ];

    /**
     * Columns each type accepts. `required` must all be present; when `one_of`
     * is set, at least one of those must be present too (the row's key).
     */
    private const COLUMNS = [
        'clients' => [
            'required' => ['name', 'type', 'address', 'contact_name', 'contact_phone', 'contact_email'],
            'optional' => ['rc_number'],
        ],
        'nxp' => [
            'required' => [
                'nxp_number', 'client', 'direction', 'product_category', 'product_description', 'quantity',
                'unit_of_measure', 'declared_value', 'currency', 'origin_country', 'destination_country', 'zone',
            ],
            'optional' => ['hs_code'],
        ],
        'inspection_requests' => [
            'required' => [],
            'one_of'   => ['nxp_number', 'record_ref'],
            'optional' => ['requested_at'],
        ],
        'assignments' => [
            'required' => ['inspector_email', 'scheduled_at', 'location_type', 'location_detail'],
            'one_of'   => ['nxp_number', 'record_ref'],
            'optional' => [],
        ],
        'trade_details' => [
            'required' => [],
            'one_of'   => ['nxp_number', 'record_ref'],
            'optional' => [
                'importer_name', 'importer_address', 'nepc_number', 'exporter_bank_name', 'importer_bank_name',
                'bank_reference', 'invoice_number', 'invoice_date', 'basis_of_sale', 'method_of_payment',
                'freight_charges', 'insurance_charges',
            ],
        ],
        'shipment_details' => [
            'required' => [],
            'one_of'   => ['nxp_number', 'cci_number', 'record_ref'],
            'optional' => [
                'shipment_date', 'shipping_agent', 'carrier_vessel', 'loading_ref_no', 'container_numbers',
                'packing_details', 'quality_remark', 'gross_weight_kg', 'net_weight_kg', 'forex_exchange_date',
                'exchange_rate', 'ness_charges_paid', 'ness_receipt_no', 'ness_actual_payable', 'ness_balance_paid',
                'ness_balance_receipt_no',
            ],
        ],
        'users' => [
            'required' => ['full_name', 'email', 'role'],
            'optional' => ['phone', 'zone', 'status', 'password'],
        ],
    ];

    public function __construct(
        private readonly PDO $pdo,
        private readonly ClientService $clients,
        private readonly ConsignmentService $consignments,
        private readonly AuditLog $audit,
        private readonly ?InspectionRequestService $requests = null,
        private readonly ?TradeDetailsRepository $tradeDetails = null,
        private readonly ?ShipmentDetailsRepository $shipmentDetails = null,
        private readonly ?UserAdminService $users = null,
        private readonly ?SchedulingService $scheduling = null,
    ) {
    }

    /** @return array{required:list<string>,optional:list<string>,one_of:list<string>} */
    public static function columnsFor(string $type): array
    {
        $cols = self::COLUMNS[$type] ?? throw new ApiException(422, 'validation_failed', 'Unknown import type.');

        return $cols + ['one_of' => []];
    }

    /** A ready-to-fill template, so nobody has to guess the column names. */
    public static function templateFor(string $type): string
    {
        $cols = self::columnsFor($type);
        $headers = [...$cols['one_of'], ...$cols['required'], ...$cols['optional']];
        $example = [
            'clients' => [
                'name' => 'Tiger Foods Ltd', 'type' => 'exporter', 'address' => '12 Marina Road, Lagos',
                'contact_name' => 'Ada Obi', 'contact_phone' => '+2348012345678', 'contact_email' => 'ada@tigerfoods.example',
                'rc_number' => 'RC123456',
            ],
            'nxp' => [
                'nxp_number' => 'AA1234567', 'client' => 'Tiger Foods Ltd', 'direction' => 'export', 'product_category' => 'Cocoa beans',
                'product_description' => 'Dried fermented cocoa beans, grade 1', 'quantity' => '25', 'unit_of_measure' => 'MT',
                'declared_value' => '75000.00', 'currency' => 'USD', 'origin_country' => 'Nigeria',
                'destination_country' => 'Netherlands', 'zone' => 'Lagos', 'hs_code' => '1801.00',
            ],
            'inspection_requests' => ['nxp_number' => 'AA1234567', 'requested_at' => '2026-10-01 09:00'],
            'assignments' => [
                'nxp_number' => 'AA1234567', 'inspector_email' => 'inspector@adwol.test', 'scheduled_at' => '2026-10-02 10:00',
                'location_type' => 'warehouse', 'location_detail' => 'Tiger Foods warehouse, Ikeja',
            ],
            'trade_details' => [
                'nxp_number' => 'AA1234567', 'importer_name' => 'Cacao Trading BV', 'importer_address' => 'Havenstraat 1, Amsterdam',
                'nepc_number' => 'NEPC/123/2026', 'exporter_bank_name' => 'First Bank of Nigeria', 'importer_bank_name' => 'ING Bank',
                'bank_reference' => 'FBN/EXP/0001', 'invoice_number' => 'INV-2026-044', 'invoice_date' => '2026-09-15',
                'basis_of_sale' => 'FOB', 'method_of_payment' => 'Letter of credit', 'freight_charges' => '1200.00',
                'insurance_charges' => '150.00',
            ],
            'shipment_details' => [
                'nxp_number' => 'AA1234567', 'shipment_date' => '2026-10-05', 'shipping_agent' => 'Seaways Agency Ltd',
                'carrier_vessel' => 'MV Atlantic Star', 'loading_ref_no' => 'BL-778812', 'container_numbers' => 'MSKU1234567',
                'packing_details' => '500 jute bags', 'quality_remark' => 'Grade 1, conforms', 'gross_weight_kg' => '25300',
                'net_weight_kg' => '25000', 'forex_exchange_date' => '2026-10-04', 'exchange_rate' => '1550.25',
                'ness_charges_paid' => '581343.75', 'ness_receipt_no' => 'NESS-2026-0091',
            ],
            'users' => [
                'full_name' => 'Chidi Okeke', 'email' => 'chidi@adwol.example', 'role' => 'inspector', 'phone' => '+2348031234567',
                'zone' => 'Lagos', 'status' => 'active',
            ],
        ][$type];

        return \App\Returns\CsvWriter::write($headers, [array_map(static fn (string $h): string => $example[$h] ?? '', $headers)]);
    }

    /**
     * Validate a file without writing anything. `$actorId` is needed for types
     * that record who made the record (inspection requests).
     *
     * @return array{type:string,rows:list<array{line:int,label:string,error:string|null}>,ok:int,failed:int}
     */
    public function preview(string $type, string $csv, ?int $actorId = null): array
    {
        return $this->run($type, $csv, commit: false, actorId: $actorId, ip: null);
    }

    /**
     * Import for real. Identical to preview() except the transaction is kept —
     * and only if every row worked.
     *
     * @return array{type:string,rows:list<array{line:int,label:string,error:string|null}>,ok:int,failed:int}
     */
    public function commit(string $type, string $csv, int $actorId, ?string $ip): array
    {
        return $this->run($type, $csv, commit: true, actorId: $actorId, ip: $ip);
    }

    /**
     * @return array{type:string,rows:list<array{line:int,label:string,error:string|null}>,ok:int,failed:int}
     */
    private function run(string $type, string $csv, bool $commit, ?int $actorId, ?string $ip): array
    {
        if (!in_array($type, self::TYPES, true)) {
            throw new ApiException(422, 'validation_failed', 'Unknown import type.');
        }

        $parsed = CsvReader::parse($csv);
        $this->assertHeaders($type, $parsed['headers']);

        // Names → uuids once, so a 500-row NXP file doesn't do 500 lookups.
        $clientsByName = $type === 'nxp' ? $this->clientIndex() : [];

        $results = [];
        $ok = $failed = 0;
        $seen = [];

        $this->pdo->beginTransaction();
        try {
            foreach ($parsed['rows'] as $row) {
                if ($row['error'] !== null) {
                    $results[] = ['line' => $row['line'], 'label' => '', 'error' => $row['error']];
                    $failed++;
                    continue;
                }

                $label = $this->labelFor($type, $row['data']);

                try {
                    $this->insert($type, $row['data'], $clientsByName, $actorId, $seen);
                    $results[] = ['line' => $row['line'], 'label' => $label, 'error' => null];
                    $ok++;
                } catch (ApiException $e) {
                    $field = $e->getDetails()['field'] ?? null;
                    $results[] = [
                        'line'  => $row['line'],
                        'label' => $label,
                        'error' => ($field !== null ? ucfirst(str_replace('_', ' ', (string) $field)) . ': ' : '') . $e->getMessage(),
                    ];
                    $failed++;
                } catch (\PDOException $e) {
                    $results[] = [
                        'line'  => $row['line'],
                        'label' => $label,
                        'error' => str_contains($e->getMessage(), 'Duplicate entry')
                            ? 'A record with these details already exists.'
                            : 'This row could not be saved.',
                    ];
                    $failed++;
                }
            }

            // All-or-nothing, and a preview never keeps anything.
            if ($commit && $failed === 0) {
                $this->pdo->commit();
            } else {
                $this->pdo->rollBack();
            }
        } catch (\Throwable $e) {
            if ($this->pdo->inTransaction()) {
                $this->pdo->rollBack();
            }
            throw $e;
        }

        if ($commit && $failed === 0) {
            $this->audit->record($actorId, 'import.' . $type, 'import', 0, null, ['rows' => $ok], $ip);
        }

        return ['type' => $type, 'rows' => $results, 'ok' => $ok, 'failed' => $failed];
    }

    /**
     * @param array<string,string> $data
     * @param array<string,string> $clientsByName
     * @param array<string,int> $seen keys already used earlier in this file
     */
    private function insert(string $type, array $data, array $clientsByName, ?int $actorId, array &$seen): void
    {
        match ($type) {
            'clients'             => $this->clients->create(Input::fromArray($this->compact($data))),
            'nxp'                 => $this->insertNxp($data, $clientsByName),
            'inspection_requests' => $this->insertRequest($data, $actorId, $seen),
            'assignments'         => $this->assign($data, $seen),
            'trade_details'       => $this->updateTrade($data, $seen),
            'shipment_details'    => $this->updateShipment($data, $seen),
            'users'               => $this->insertUser($data),
        };
    }

    /**
     * @param array<string,string> $data
     * @param array<string,string> $clientsByName
     */
    private function insertNxp(array $data, array $clientsByName): void
    {
        $name = $data['client'] ?? '';
        $clientUuid = $clientsByName[mb_strtolower(trim($name))] ?? null;
        if ($clientUuid === null) {
            throw new ApiException(422, 'validation_failed', "No client is named \"{$name}\". Import the clients first, or correct the name.", ['field' => 'client']);
        }

        $fields = $this->compact($data);
        // The sheet says "nxp_number"; the record field is form_nxp_number.
        $nxp = $fields['nxp_number'] ?? $fields['form_nxp_number'] ?? null;
        unset($fields['client'], $fields['nxp_number'], $fields['form_nxp_number']);
        if ($nxp !== null) {
            $fields['form_nxp_number'] = $nxp;
        }
        $fields['client_uuid'] = $clientUuid;

        $this->consignments->create(Input::fromArray($fields));
    }

    /**
     * @param array<string,string> $data
     * @param array<string,int> $seen
     */
    private function insertRequest(array $data, ?int $actorId, array &$seen): void
    {
        if ($this->requests === null || $actorId === null) {
            throw new \LogicException('Inspection-request import needs the request service and the signed-in user.');
        }

        $record = $this->nxpRecord($data);
        $this->once($seen, 'request:' . $record['id'], 'This NXP record appears more than once in the file.');

        $open = $this->pdo->prepare("SELECT COUNT(*) FROM inspection_requests WHERE consignment_id = :c AND status IN ('pending', 'scheduled')");
        $open->execute(['c' => $record['id']]);
        if ((int) $open->fetchColumn() > 0) {
            throw new ApiException(422, 'validation_failed', 'This NXP record already has an open inspection request.');
        }

        $fields = ['consignment_uuid' => $record['uuid']];
        if (trim($data['requested_at'] ?? '') !== '') {
            $fields['requested_at'] = trim($data['requested_at']);
        }

        $this->requests->create(Input::fromArray($fields), $actorId);
    }

    /**
     * Assign an inspector to the NXP record's open request — the same action as
     * "Assign inspector" on the request page (SchedulingService).
     *
     * @param array<string,string> $data
     * @param array<string,int> $seen
     */
    private function assign(array $data, array &$seen): void
    {
        if ($this->scheduling === null) {
            throw new \LogicException('Assignment import needs the scheduling service.');
        }

        $record = $this->nxpRecord($data);
        $this->once($seen, 'assign:' . $record['id'], 'This NXP record appears more than once in the file.');

        $req = $this->pdo->prepare(
            "SELECT uuid, id FROM inspection_requests WHERE consignment_id = :c AND status IN ('pending', 'scheduled')
          ORDER BY requested_at DESC, id DESC LIMIT 1"
        );
        $req->execute(['c' => $record['id']]);
        $request = $req->fetch();
        if ($request === false) {
            throw new ApiException(422, 'validation_failed', 'This NXP record has no open inspection request. Raise the request first.');
        }

        $live = $this->pdo->prepare("SELECT COUNT(*) FROM inspections WHERE inspection_request_id = :r AND status <> 'rejected'");
        $live->execute(['r' => $request['id']]);
        if ((int) $live->fetchColumn() > 0) {
            throw new ApiException(422, 'validation_failed', 'An inspector is already assigned to this request.');
        }

        $email = mb_strtolower(trim($data['inspector_email'] ?? ''));
        $who = $this->pdo->prepare('SELECT uuid FROM users WHERE email = :e LIMIT 1');
        $who->execute(['e' => $email]);
        $inspectorUuid = $who->fetchColumn();
        if ($inspectorUuid === false) {
            throw new ApiException(422, 'validation_failed', "No user has the email \"{$email}\".", ['field' => 'inspector_email']);
        }

        $this->scheduling->schedule((string) $request['uuid'], Input::fromArray([
            'inspector_uuid'  => (string) $inspectorUuid,
            'scheduled_at'    => trim($data['scheduled_at'] ?? ''),
            'location_type'   => mb_strtolower(trim($data['location_type'] ?? '')),
            'location_detail' => trim($data['location_detail'] ?? ''),
        ]));
    }

    /**
     * @param array<string,string> $data
     * @param array<string,int> $seen
     */
    private function updateTrade(array $data, array &$seen): void
    {
        $record = $this->nxpRecord($data);
        $this->once($seen, 'trade:' . $record['id'], 'This NXP record appears more than once in the file.');

        $changes = $this->cells($data, self::TRADE_COLUMNS);
        if ($changes === []) {
            throw new ApiException(422, 'validation_failed', 'Nothing to update: every detail cell on this row is blank.');
        }

        $repo = $this->tradeDetails ?? new TradeDetailsRepository($this->pdo);
        $repo->upsert($record['id'], array_merge($repo->forConsignment($record['id']) ?? [], $changes));
    }

    /**
     * @param array<string,string> $data
     * @param array<string,int> $seen
     */
    private function updateShipment(array $data, array &$seen): void
    {
        $inspectionId = $this->inspectionFor($data);
        $this->once($seen, 'shipment:' . $inspectionId, 'This inspection appears more than once in the file.');

        $changes = $this->cells($data, self::SHIPMENT_COLUMNS);
        if ($changes === []) {
            throw new ApiException(422, 'validation_failed', 'Nothing to update: every detail cell on this row is blank.');
        }

        $repo = $this->shipmentDetails ?? new ShipmentDetailsRepository($this->pdo);
        $repo->upsert($inspectionId, array_merge($repo->forInspection($inspectionId) ?? [], $changes));
    }

    /** @param array<string,string> $data */
    private function insertUser(array $data): void
    {
        if ($this->users === null) {
            throw new \LogicException('User import needs the user service.');
        }

        $fields = $this->compact($data);
        $fields['email'] = mb_strtolower(trim($fields['email'] ?? ''));
        $fields['role'] = str_replace([' ', '-'], '_', mb_strtolower(trim($fields['role'] ?? '')));
        if ($fields['role'] === 'board_of_directors') {
            $fields['role'] = 'board';
        }
        if (isset($fields['status'])) {
            $fields['status'] = mb_strtolower(trim($fields['status']));
        }
        // No password in the sheet: a long random one nobody knows. The person
        // sets their own with "Forgot password", or an admin resets it.
        if (!isset($fields['password'])) {
            $fields['password'] = rtrim(strtr(base64_encode(random_bytes(24)), '+/', '-_'), '=');
        }

        $this->users->create(Input::fromArray($fields));
    }

    /**
     * The NXP record a row points at: by NXP number, or by the record reference
     * shown on the record's page (for imports, which have no NXP number).
     *
     * @param array<string,string> $data
     * @return array{id:int,uuid:string}
     */
    private function nxpRecord(array $data): array
    {
        $nxp = trim($data['nxp_number'] ?? '');
        $ref = trim($data['record_ref'] ?? '');

        if ($nxp !== '') {
            $stmt = $this->pdo->prepare('SELECT id, uuid FROM consignments WHERE form_nxp_number = :n LIMIT 1');
            $stmt->execute(['n' => $nxp]);
            $row = $stmt->fetch();
            if ($row === false) {
                throw new ApiException(422, 'validation_failed', "No NXP record has the number \"{$nxp}\".", ['field' => 'nxp_number']);
            }
        } elseif ($ref !== '') {
            $stmt = $this->pdo->prepare('SELECT id, uuid FROM consignments WHERE uuid = :u LIMIT 1');
            $stmt->execute(['u' => $ref]);
            $row = $stmt->fetch();
            if ($row === false) {
                throw new ApiException(422, 'validation_failed', "No NXP record has the reference \"{$ref}\".", ['field' => 'record_ref']);
            }
        } else {
            throw new ApiException(422, 'validation_failed', 'Give the NXP number (or, for an import, the record reference).', ['field' => 'nxp_number']);
        }

        return ['id' => (int) $row['id'], 'uuid' => (string) $row['uuid']];
    }

    /**
     * The inspection a shipment row belongs to: the one a CCI number was issued
     * on, or the NXP record's latest inspection that wasn't rejected.
     *
     * @param array<string,string> $data
     */
    private function inspectionFor(array $data): int
    {
        $cci = trim($data['cci_number'] ?? '');
        if ($cci !== '') {
            $stmt = $this->pdo->prepare('SELECT inspection_id FROM documents WHERE document_number = :n LIMIT 1');
            $stmt->execute(['n' => $cci]);
            $id = $stmt->fetchColumn();
            if ($id === false) {
                throw new ApiException(422, 'validation_failed', "No certificate has the number \"{$cci}\".", ['field' => 'cci_number']);
            }

            return (int) $id;
        }

        $record = $this->nxpRecord($data);
        $stmt = $this->pdo->prepare(
            "SELECT i.id FROM inspections i JOIN inspection_requests r ON r.id = i.inspection_request_id
              WHERE r.consignment_id = :c AND i.status <> 'rejected'
           ORDER BY i.scheduled_at DESC, i.id DESC LIMIT 1"
        );
        $stmt->execute(['c' => $record['id']]);
        $id = $stmt->fetchColumn();
        if ($id === false) {
            throw new ApiException(422, 'validation_failed', 'This NXP record has no inspection yet, so there is nothing to attach shipment details to.');
        }

        return (int) $id;
    }

    /**
     * The filled-in detail cells of a row, checked and normalised to what the
     * database stores. Blank cells are left out (they mean "leave as it is").
     *
     * @param array<string,string> $data
     * @param array<string,int|string|list<string>> $spec column => max length | 'date' | 'money' | 'rate' | allowed values
     * @return array<string,string>
     */
    private function cells(array $data, array $spec): array
    {
        $out = [];
        foreach ($spec as $col => $rule) {
            $v = trim($data[$col] ?? '');
            if ($v === '') {
                continue;
            }

            if (is_int($rule)) {
                if (mb_strlen($v) > $rule) {
                    throw new ApiException(422, 'validation_failed', "Must be at most {$rule} characters.", ['field' => $col]);
                }
                $out[$col] = $v;
            } elseif (is_array($rule)) {
                $up = strtoupper($v);
                if (!in_array($up, $rule, true)) {
                    throw new ApiException(422, 'validation_failed', 'Must be one of ' . implode(', ', $rule) . '.', ['field' => $col]);
                }
                $out[$col] = $up;
            } elseif ($rule === 'date') {
                $out[$col] = self::date($v, $col);
            } else {
                $n = str_replace([',', ' '], '', $v);
                if (!is_numeric($n) || (float) $n < 0 || ($rule === 'rate' && (float) $n <= 0)) {
                    throw new ApiException(422, 'validation_failed', $rule === 'rate' ? 'Must be a number greater than 0.' : 'Must be a number (0 or more).', ['field' => $col]);
                }
                $out[$col] = $n;
            }
        }

        return $out;
    }

    /** "2026-09-21" or "21/09/2026" (day first, as written in Nigeria) → "2026-09-21". */
    private static function date(string $v, string $field): string
    {
        // Each input format, and the spellings of it that count as an exact
        // round-trip (spreadsheets write 1/9/2026 as readily as 01/09/2026).
        foreach (['!Y-m-d' => ['Y-m-d'], '!d/m/Y' => ['d/m/Y', 'j/n/Y', 'd/n/Y', 'j/m/Y']] as $format => $spellings) {
            $d = \DateTimeImmutable::createFromFormat($format, $v);
            if ($d === false) {
                continue;
            }
            foreach ($spellings as $spelling) {
                if ($d->format($spelling) === $v) {
                    return $d->format('Y-m-d');
                }
            }
        }

        throw new ApiException(422, 'validation_failed', 'Must be a date like 2026-09-21 or 21/09/2026.', ['field' => $field]);
    }

    /** @param array<string,int> $seen */
    private function once(array &$seen, string $key, string $message): void
    {
        if (isset($seen[$key])) {
            throw new ApiException(422, 'validation_failed', $message);
        }
        $seen[$key] = 1;
    }

    /**
     * Drop empty cells so an unset optional column behaves like "not supplied"
     * rather than "supplied as an empty string".
     *
     * @param array<string,string> $data
     * @return array<string,string>
     */
    private function compact(array $data): array
    {
        return array_filter($data, static fn (string $v): bool => $v !== '');
    }

    /** @param array<string,string> $data */
    private function labelFor(string $type, array $data): string
    {
        $join = static fn (string ...$parts): string => implode(' — ', array_filter($parts, static fn (string $v): bool => $v !== ''));

        return match ($type) {
            'clients' => $data['name'] ?? '',
            'nxp'     => $join($data['nxp_number'] ?? $data['form_nxp_number'] ?? '', $data['client'] ?? '', $data['product_category'] ?? ''),
            'users'   => $join($data['full_name'] ?? '', $data['email'] ?? ''),
            default   => $join(
                ($data['cci_number'] ?? '') !== '' ? 'CCI ' . $data['cci_number'] : '',
                ($data['nxp_number'] ?? '') !== '' ? 'NXP ' . $data['nxp_number'] : '',
                ($data['record_ref'] ?? '') !== '' && ($data['nxp_number'] ?? '') === '' ? 'Ref ' . $data['record_ref'] : '',
            ),
        };
    }

    /** @return array<string,string> lower-cased client name => uuid */
    private function clientIndex(): array
    {
        $index = [];
        foreach ($this->pdo->query('SELECT uuid, name FROM clients')->fetchAll() as $row) {
            $index[mb_strtolower(trim((string) $row['name']))] = (string) $row['uuid'];
        }

        return $index;
    }

    /** @param list<string> $headers */
    private function assertHeaders(string $type, array $headers): void
    {
        // Sheets exported before the rename call the column "form_nxp_number".
        if (in_array('form_nxp_number', $headers, true)) {
            $headers[] = 'nxp_number';
        }
        $cols = self::columnsFor($type);
        $missing = array_diff($cols['required'], $headers);
        if ($missing !== []) {
            throw new ApiException(
                422,
                'validation_failed',
                'That file is missing these columns: ' . implode(', ', $missing) . '. Download the template to see the expected header row.',
            );
        }
        if ($cols['one_of'] !== [] && array_intersect($cols['one_of'], $headers) === []) {
            throw new ApiException(
                422,
                'validation_failed',
                'That file needs a column saying which record each row is for: ' . implode(' or ', $cols['one_of']) . '.',
            );
        }
    }
}
